### ISSUE TITLE
TypeError: str.replace is not a function

### ISSUE THREAD

**Issue by NeonGamerBot-QK** [FightFarewellFearless/anime-react-native#2]
# TypeError: str.replace is not a function

happens when i open it on codespace on node version 16.

Stack:
```js
TypeError: str.replace is not a function
    at inlineString (/workspaces/anime-react-native/node_modules/@react-native-community/cli-tools/build/errors.js:25:33)
    at new CLIError (/workspaces/anime-react-native/node_modules/@react-native-community/cli-tools/build/errors.js:13:11)
    at getProjectInfo (/workspaces/anime-react-native/node_modules/@react-native-community/cli-platform-ios/build/tools/getProjectInfo.js:29:11)
    at Object.runIOS [as func] (/workspaces/anime-react-native/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:82:58)
    at Command.handleAction (/workspaces/anime-react-native/node_modules/@react-native-community/cli/build/index.js:108:23)
    at Command.listener [as _actionHandler] (/workspaces/anime-react-native/node_modules/commander/lib/command.js:482:17)
    at /workspaces/anime-react-native/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/workspaces/anime-react-native/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/workspaces/anime-react-native/node_modules/commander/lib/command.js:1283:27)
    at /workspaces/anime-react-native/node_modules/commander/lib/command.js:1081:27
```

**Comment by FightFarewellFearless** [comment]
https://github.com/react-native-community/cli/issues/1883

Try this

**Comment by FightFarewellFearless** [comment]
Try upgrading the react native cli, or install from the github repo, they have fixed it https://github.com/react-native-community/cli/pull/1909

**Comment by FightFarewellFearless** [comment]
Do u build for ios? Unfortunately this app is not supported ios yet because i dont setup some of third party modules, but u can try to setup and open pull request

**Comment by NeonGamerBot-QK** [comment]
no i just run this on a web server and i get this error.

**Comment by FightFarewellFearless** [comment]
Can u send the command?

**Comment by FightFarewellFearless** [comment]
Have u upgrade?

**Comment by FightFarewellFearless** [comment]
> The command was: `yarn start`

Try `npm run android` or `react-native run-android`

**Comment by NeonGamerBot-QK** [comment]
i dont have any android device to test it with on git codespaces

**Comment by FightFarewellFearless** [comment]
Uh, then why u run a start command?, u cant debug without phone

**Comment by FightFarewellFearless** [comment]
Yes, but this app is not support react-native-web nor expo. Because some dependecies are only available to android

**Comment by zacchaeuschok** [comment]
I ran this and the problem was fixed:

```
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
```

**Comment by FightFarewellFearless** [comment]
> I ran this and the problem was fixed:
> 
> ```
> sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
> ```

Tysm!!
